FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY DungeonServer/ DungeonServer/
COPY contracts/ contracts/

WORKDIR "/app/DungeonServer/DungeonServer.Service"
RUN dotnet restore "DungeonServer.Service.csproj"
RUN dotnet publish "DungeonServer.Service.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 8081
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "DungeonServer.Service.dll"]