using System.Collections.Concurrent;
using DungeonServer.Application.Dungeon.Rooms.Models;

namespace DungeonServer.Application.Dungeon.Rooms.Storage;

public class InMemoryRoomStore : IRoomStore
{
    private sealed class LockableRoomState
    {
        public RoomState RoomState { get; }
        public SemaphoreSlim Gate { get; } = new(initialCount: 1, maxCount: 1);

        public LockableRoomState(int roomId, RoomState state)
        {
            RoomState = state;
            RoomState.RoomId = roomId;
        }
    }

    private readonly ConcurrentDictionary<int, LockableRoomState> _roomStates = new();

    private int _nextRoomId;

    public Task<RoomStateSnapshot> CreateRoomAsync(RoomState room, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (room.RoomId != 0)
        {
            throw new ArgumentException("Room ID must be '0' because it is generated by the store.", nameof(room));
        }

        int roomId = Interlocked.Increment(ref _nextRoomId);
        var entry = new LockableRoomState(roomId, room);

        if (!_roomStates.TryAdd(roomId, entry))
        {
            throw new InvalidOperationException("Failed to create room due to id collision");
        }

        return Task.FromResult(RoomStateSnapshot.From(entry.RoomState));
    }

    public async Task<RoomStateSnapshot> UpdateRoomAsync(int roomId, Action<RoomState> updateAction,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            throw new KeyNotFoundException($"Room Id {roomId} does not exist.");
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            updateAction(room.RoomState);
            return RoomStateSnapshot.From(room.RoomState);
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public async Task<RoomStateSnapshot?> GetRoomAsync(int roomId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            return null;
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            return RoomStateSnapshot.From(room.RoomState);
        }
        finally
        {
            room.Gate.Release();
        }
    }
}