using System.Collections.Concurrent;
using DungeonServer.Application.Core.Rooms.Models;

namespace DungeonServer.Application.Core.Rooms.Storage;

public class InMemoryRoomStore : IRoomStore
{
    private sealed class LockableRoomState
    {
        public RoomState RoomState { get; }
        public SemaphoreSlim Gate { get; } = new(initialCount: 1, maxCount: 1);

        public LockableRoomState(int roomId, RoomState state)
        {
            RoomState = state;
            RoomState.RoomId = roomId;
        }
    }

    private readonly ConcurrentDictionary<int, LockableRoomState> _roomStates = new();

    private readonly IRoomSubscriptionRegistry _subscriptionRegistry;

    private int _nextRoomId;

    public InMemoryRoomStore(IRoomSubscriptionRegistry subscriptionRegistry)
    {
        _subscriptionRegistry = subscriptionRegistry;
    }

    public Task<RoomStateSnapshot> CreateRoomAsync(RoomState room, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (room.RoomId != 0)
        {
            throw new ArgumentException("Room ID must be '0' because it is generated by the store.", nameof(room));
        }

        int roomId = Interlocked.Increment(ref _nextRoomId);
        var entry = new LockableRoomState(roomId, room);

        if (!_roomStates.TryAdd(roomId, entry))
        {
            throw new InvalidOperationException("Failed to create room due to id collision");
        }

        RoomStateSnapshot snapshot = RoomStateSnapshot.From(entry.RoomState);
        _subscriptionRegistry.PublishUpdate(roomId, snapshot, RoomUpdateContext.Broadcast());

        return Task.FromResult(snapshot);
    }

    public async Task<RoomStateSnapshot> UpdateRoomAsync(int roomId, Action<RoomState> updateAction, RoomUpdateContext context,
        CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            throw new KeyNotFoundException($"Room Id {roomId} does not exist.");
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            updateAction(room.RoomState);
            var snapshot = RoomStateSnapshot.From(room.RoomState);
            _subscriptionRegistry.PublishUpdate(roomId, snapshot, context);
            return snapshot;
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public async Task<RoomStateSnapshot?> GetRoomAsync(int roomId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            return null;
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            return RoomStateSnapshot.From(room.RoomState);
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public async Task PublishRoomUpdateAsync(int roomId, RoomUpdateContext context, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            return;
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            RoomStateSnapshot snapshot = RoomStateSnapshot.From(room.RoomState);
            _subscriptionRegistry.PublishUpdate(roomId, snapshot, context);
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public IAsyncEnumerable<RoomStateSnapshot> SubscribeRoomAsync(int roomId, int subscriberPlayerId, CancellationToken ct)
    {
        return _subscriptionRegistry.SubscribeAsync(roomId, subscriberPlayerId, ct);
    }
}