using System.Collections.Concurrent;
using DungeonServer.Application.Core.Player.Models;
using DungeonServer.Application.Core.Player.Storage;
using DungeonServer.Application.Core.Rooms.Models;
using DungeonServer.Application.Core.Rooms.Storage;
using DungeonServer.Application.Core.Shared;

namespace DungeonServer.Infrastructure.InMemory.Rooms;

public class InMemoryRoomStore : IRoomStore
{
    private sealed class LockableRoomState
    {
        public RoomState RoomState { get; }
        public SemaphoreSlim Gate { get; } = new(initialCount: 1, maxCount: 1);

        public LockableRoomState(int roomId, RoomState state)
        {
            RoomState = state;
            RoomState.RoomId = roomId;
        }
    }

    private readonly ConcurrentDictionary<int, LockableRoomState> _roomStates = new();
    private readonly IRoomSubscriptionRegistry _subscriptionRegistry;
    private readonly IPlayerStore _playerStore;
    private int _nextRoomId;

    public InMemoryRoomStore(IRoomSubscriptionRegistry subscriptionRegistry, IPlayerStore playerStore)
    {
        _subscriptionRegistry = subscriptionRegistry;
        _playerStore = playerStore;
    }

    public async Task<RoomStateSnapshot> CreateRoomAsync(RoomState room, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (room.RoomId != RoomConstants.InvalidRoomId)
        {
            throw new ArgumentException("Room ID must be '0' because it is generated by the store.", nameof(room));
        }

        int roomId = Interlocked.Increment(ref _nextRoomId);
        var entry = new LockableRoomState(roomId, room);

        if (!_roomStates.TryAdd(roomId, entry))
        {
            throw new InvalidOperationException("Failed to create room due to id collision");
        }

        RoomStateSnapshot snapshot = RoomStateSnapshot.From(entry.RoomState);
        await _subscriptionRegistry.PublishUpdateAsync(roomId, snapshot, RoomUpdateContext.Broadcast(), ct);

        return snapshot;
    }

    public async Task<RoomStateSnapshot> AddPlayerToRoomAsync(int roomId, int playerId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            throw new KeyNotFoundException($"Room Id {roomId} does not exist.");
        }

        PlayerSnapshot? player = await _playerStore.GetPlayerAsync(playerId, ct);
        if (player == null)
        {
            throw new KeyNotFoundException($"Player {playerId} not found.");
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            if (room.RoomState.Players.Any(p => p.PlayerId == playerId))
            {
                return RoomStateSnapshot.From(room.RoomState);
            }

            room.RoomState.Players.Add(player);

            RoomStateSnapshot snapshot = RoomStateSnapshot.From(room.RoomState);
            await _subscriptionRegistry.PublishUpdateAsync(roomId, snapshot, RoomUpdateContext.Broadcast(), ct);

            return snapshot;
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public async Task<RoomStateSnapshot> RemovePlayerFromRoomAsync(int roomId, int playerId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            throw new KeyNotFoundException($"Room Id {roomId} does not exist.");
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            PlayerSnapshot? player = room.RoomState.Players.FirstOrDefault(p => p.PlayerId == playerId);
            if (player != null)
            {
                room.RoomState.Players.Remove(player);
            }
            
            var snapshot = RoomStateSnapshot.From(room.RoomState);
            await _subscriptionRegistry.PublishUpdateAsync(roomId, snapshot, RoomUpdateContext.Broadcast(), ct);
            return snapshot;
        }
        finally
        {
            room.Gate.Release();
        }
    }

    public async Task<RoomStateSnapshot?> GetRoomAsync(int roomId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (!_roomStates.TryGetValue(roomId, out LockableRoomState? room))
        {
            return null;
        }

        await room.Gate.WaitAsync(ct);
        try
        {
            return RoomStateSnapshot.From(room.RoomState);
        }
        finally
        {
            room.Gate.Release();
        }
    }

    /// <summary>
    /// Tell subscribers that an update has occurred within the given room.
    /// </summary>
    public async Task PublishRoomUpdateAsync(int roomId, RoomUpdateContext context, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        RoomStateSnapshot? snapshot = await GetRoomAsync(roomId, ct);
        if (snapshot != null)
        {
            await _subscriptionRegistry.PublishUpdateAsync(roomId, snapshot, context, ct);
        }
    }

    public async Task LinkRoomsAsync(int roomIdA, int roomIdB, Direction directionFromAToB, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (roomIdA == roomIdB)
        {
            throw new ArgumentException("Cannot link a room to itself.");
        }

        await SafeUpdateRoomStates(
            roomIdA,
            roomIdB,
            (roomA, roomB) =>
            {
                roomA.RoomState.Exits[directionFromAToB] = roomIdB;
                roomB.RoomState.Exits[Helpers.GetOppositeDirection(directionFromAToB)] = roomIdA;
            },
            ct);
    }

    public async Task SwapRoomsAsync(int playerId, int fromRoomId, int toRoomId, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        PlayerSnapshot? player = await _playerStore.GetPlayerAsync(playerId, ct);
        if (player == null)
        {
            throw new KeyNotFoundException($"Player {playerId} not found.");
        }

        await SafeUpdateRoomStates(
            fromRoomId,
            toRoomId,
            (fromRoom, toRoom) =>
            {
                PlayerSnapshot? occupant = fromRoom.RoomState.Players.FirstOrDefault(p => p.PlayerId == playerId);
                if (occupant == null)
                {
                    throw new KeyNotFoundException($"Player {playerId} not in source room.");
                }

                fromRoom.RoomState.Players.Remove(occupant);

                if (toRoom.RoomState.Players.All(p => p.PlayerId != playerId))
                {
                    toRoom.RoomState.Players.Add(player);
                }
            },
            ct);
    }

    public IAsyncEnumerable<RoomStateSnapshot> SubscribeRoomAsync(
        int subscriberPlayerId,
        int roomId,
        CancellationToken ct)
    {
        return _subscriptionRegistry.SubscribeAsync(subscriberPlayerId, roomId, ct);
    }

    private async Task SafeUpdateRoomStates(
        int roomIdA,
        int roomIdB,
        Action<LockableRoomState, LockableRoomState> update,
        CancellationToken ct)
    {
        if (!_roomStates.TryGetValue(roomIdA, out LockableRoomState? roomA))
        {
            throw new KeyNotFoundException($"Room Id {roomIdA} does not exist.");
        }

        if (!_roomStates.TryGetValue(roomIdB, out LockableRoomState? roomB))
        {
            throw new KeyNotFoundException($"Room Id {roomIdB} does not exist.");
        }

        // Always lock the one with the smaller ID first to avoid deadlocks
        LockableRoomState first = roomIdA < roomIdB ? roomA : roomB;
        LockableRoomState second = roomIdA < roomIdB ? roomB : roomA;

        await first.Gate.WaitAsync(ct);
        try
        {
            await second.Gate.WaitAsync(ct);
            try
            {
                update(roomA, roomB);

                await _subscriptionRegistry.PublishUpdateAsync(
                    roomIdA,
                    RoomStateSnapshot.From(roomA.RoomState),
                    RoomUpdateContext.Broadcast(),
                    ct);
                await _subscriptionRegistry.PublishUpdateAsync(
                    roomIdB,
                    RoomStateSnapshot.From(roomB.RoomState),
                    RoomUpdateContext.Broadcast(),
                    ct);
            }
            finally
            {
                second.Gate.Release();
            }
        }
        finally
        {
            first.Gate.Release();
        }
    }
}