// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_protocol.proto

#ifndef PROTOBUF_INCLUDED_game_5fprotocol_2eproto
#define PROTOBUF_INCLUDED_game_5fprotocol_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_game_5fprotocol_2eproto 

namespace protobuf_game_5fprotocol_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_game_5fprotocol_2eproto
namespace dungeonGame {
namespace protocol {
class DungeonRoom;
class DungeonRoomDefaultTypeInternal;
extern DungeonRoomDefaultTypeInternal _DungeonRoom_default_instance_;
class Enemy;
class EnemyDefaultTypeInternal;
extern EnemyDefaultTypeInternal _Enemy_default_instance_;
class Item;
class ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
class RoomRequest;
class RoomRequestDefaultTypeInternal;
extern RoomRequestDefaultTypeInternal _RoomRequest_default_instance_;
}  // namespace protocol
}  // namespace dungeonGame
namespace google {
namespace protobuf {
template<> ::dungeonGame::protocol::DungeonRoom* Arena::CreateMaybeMessage<::dungeonGame::protocol::DungeonRoom>(Arena*);
template<> ::dungeonGame::protocol::Enemy* Arena::CreateMaybeMessage<::dungeonGame::protocol::Enemy>(Arena*);
template<> ::dungeonGame::protocol::Item* Arena::CreateMaybeMessage<::dungeonGame::protocol::Item>(Arena*);
template<> ::dungeonGame::protocol::RoomRequest* Arena::CreateMaybeMessage<::dungeonGame::protocol::RoomRequest>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dungeonGame {
namespace protocol {

// ===================================================================

class DungeonRoom : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dungeonGame.protocol.DungeonRoom) */ {
 public:
  DungeonRoom();
  virtual ~DungeonRoom();

  DungeonRoom(const DungeonRoom& from);

  inline DungeonRoom& operator=(const DungeonRoom& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DungeonRoom(DungeonRoom&& from) noexcept
    : DungeonRoom() {
    *this = ::std::move(from);
  }

  inline DungeonRoom& operator=(DungeonRoom&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DungeonRoom& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DungeonRoom* internal_default_instance() {
    return reinterpret_cast<const DungeonRoom*>(
               &_DungeonRoom_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DungeonRoom* other);
  friend void swap(DungeonRoom& a, DungeonRoom& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DungeonRoom* New() const final {
    return CreateMaybeMessage<DungeonRoom>(NULL);
  }

  DungeonRoom* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DungeonRoom>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DungeonRoom& from);
  void MergeFrom(const DungeonRoom& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DungeonRoom* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
  int initial_enemies_size() const;
  void clear_initial_enemies();
  static const int kInitialEnemiesFieldNumber = 5;
  ::dungeonGame::protocol::Enemy* mutable_initial_enemies(int index);
  ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Enemy >*
      mutable_initial_enemies();
  const ::dungeonGame::protocol::Enemy& initial_enemies(int index) const;
  ::dungeonGame::protocol::Enemy* add_initial_enemies();
  const ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Enemy >&
      initial_enemies() const;

  // repeated .dungeonGame.protocol.Item spawnable_items = 6;
  int spawnable_items_size() const;
  void clear_spawnable_items();
  static const int kSpawnableItemsFieldNumber = 6;
  ::dungeonGame::protocol::Item* mutable_spawnable_items(int index);
  ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Item >*
      mutable_spawnable_items();
  const ::dungeonGame::protocol::Item& spawnable_items(int index) const;
  ::dungeonGame::protocol::Item* add_spawnable_items();
  const ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Item >&
      spawnable_items() const;

  // string room_type = 2;
  void clear_room_type();
  static const int kRoomTypeFieldNumber = 2;
  const ::std::string& room_type() const;
  void set_room_type(const ::std::string& value);
  #if LANG_CXX11
  void set_room_type(::std::string&& value);
  #endif
  void set_room_type(const char* value);
  void set_room_type(const char* value, size_t size);
  ::std::string* mutable_room_type();
  ::std::string* release_room_type();
  void set_allocated_room_type(::std::string* room_type);

  // int32 room_id = 1;
  void clear_room_id();
  static const int kRoomIdFieldNumber = 1;
  ::google::protobuf::int32 room_id() const;
  void set_room_id(::google::protobuf::int32 value);

  // int32 width = 3;
  void clear_width();
  static const int kWidthFieldNumber = 3;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // int32 height = 4;
  void clear_height();
  static const int kHeightFieldNumber = 4;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dungeonGame.protocol.DungeonRoom)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Enemy > initial_enemies_;
  ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Item > spawnable_items_;
  ::google::protobuf::internal::ArenaStringPtr room_type_;
  ::google::protobuf::int32 room_id_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_game_5fprotocol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Enemy : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dungeonGame.protocol.Enemy) */ {
 public:
  Enemy();
  virtual ~Enemy();

  Enemy(const Enemy& from);

  inline Enemy& operator=(const Enemy& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Enemy(Enemy&& from) noexcept
    : Enemy() {
    *this = ::std::move(from);
  }

  inline Enemy& operator=(Enemy&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Enemy& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Enemy* internal_default_instance() {
    return reinterpret_cast<const Enemy*>(
               &_Enemy_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Enemy* other);
  friend void swap(Enemy& a, Enemy& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Enemy* New() const final {
    return CreateMaybeMessage<Enemy>(NULL);
  }

  Enemy* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Enemy>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Enemy& from);
  void MergeFrom(const Enemy& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Enemy* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // float x = 2;
  void clear_x();
  static const int kXFieldNumber = 2;
  float x() const;
  void set_x(float value);

  // float y = 3;
  void clear_y();
  static const int kYFieldNumber = 3;
  float y() const;
  void set_y(float value);

  // int32 health = 4;
  void clear_health();
  static const int kHealthFieldNumber = 4;
  ::google::protobuf::int32 health() const;
  void set_health(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dungeonGame.protocol.Enemy)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  float x_;
  float y_;
  ::google::protobuf::int32 health_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_game_5fprotocol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Item : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dungeonGame.protocol.Item) */ {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(Item&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Item* other);
  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Item* New() const final {
    return CreateMaybeMessage<Item>(NULL);
  }

  Item* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 item_id = 1;
  void clear_item_id();
  static const int kItemIdFieldNumber = 1;
  ::google::protobuf::int32 item_id() const;
  void set_item_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dungeonGame.protocol.Item)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 item_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_game_5fprotocol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoomRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dungeonGame.protocol.RoomRequest) */ {
 public:
  RoomRequest();
  virtual ~RoomRequest();

  RoomRequest(const RoomRequest& from);

  inline RoomRequest& operator=(const RoomRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoomRequest(RoomRequest&& from) noexcept
    : RoomRequest() {
    *this = ::std::move(from);
  }

  inline RoomRequest& operator=(RoomRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoomRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomRequest* internal_default_instance() {
    return reinterpret_cast<const RoomRequest*>(
               &_RoomRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(RoomRequest* other);
  friend void swap(RoomRequest& a, RoomRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoomRequest* New() const final {
    return CreateMaybeMessage<RoomRequest>(NULL);
  }

  RoomRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoomRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoomRequest& from);
  void MergeFrom(const RoomRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 seed = 1;
  void clear_seed();
  static const int kSeedFieldNumber = 1;
  ::google::protobuf::int32 seed() const;
  void set_seed(::google::protobuf::int32 value);

  // int32 floor_level = 2;
  void clear_floor_level();
  static const int kFloorLevelFieldNumber = 2;
  ::google::protobuf::int32 floor_level() const;
  void set_floor_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dungeonGame.protocol.RoomRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 seed_;
  ::google::protobuf::int32 floor_level_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_game_5fprotocol_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DungeonRoom

// int32 room_id = 1;
inline void DungeonRoom::clear_room_id() {
  room_id_ = 0;
}
inline ::google::protobuf::int32 DungeonRoom::room_id() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.room_id)
  return room_id_;
}
inline void DungeonRoom::set_room_id(::google::protobuf::int32 value) {
  
  room_id_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.DungeonRoom.room_id)
}

// string room_type = 2;
inline void DungeonRoom::clear_room_type() {
  room_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DungeonRoom::room_type() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.room_type)
  return room_type_.GetNoArena();
}
inline void DungeonRoom::set_room_type(const ::std::string& value) {
  
  room_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.DungeonRoom.room_type)
}
#if LANG_CXX11
inline void DungeonRoom::set_room_type(::std::string&& value) {
  
  room_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dungeonGame.protocol.DungeonRoom.room_type)
}
#endif
inline void DungeonRoom::set_room_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  room_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dungeonGame.protocol.DungeonRoom.room_type)
}
inline void DungeonRoom::set_room_type(const char* value, size_t size) {
  
  room_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dungeonGame.protocol.DungeonRoom.room_type)
}
inline ::std::string* DungeonRoom::mutable_room_type() {
  
  // @@protoc_insertion_point(field_mutable:dungeonGame.protocol.DungeonRoom.room_type)
  return room_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DungeonRoom::release_room_type() {
  // @@protoc_insertion_point(field_release:dungeonGame.protocol.DungeonRoom.room_type)
  
  return room_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DungeonRoom::set_allocated_room_type(::std::string* room_type) {
  if (room_type != NULL) {
    
  } else {
    
  }
  room_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), room_type);
  // @@protoc_insertion_point(field_set_allocated:dungeonGame.protocol.DungeonRoom.room_type)
}

// int32 width = 3;
inline void DungeonRoom::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 DungeonRoom::width() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.width)
  return width_;
}
inline void DungeonRoom::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.DungeonRoom.width)
}

// int32 height = 4;
inline void DungeonRoom::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 DungeonRoom::height() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.height)
  return height_;
}
inline void DungeonRoom::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.DungeonRoom.height)
}

// repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
inline int DungeonRoom::initial_enemies_size() const {
  return initial_enemies_.size();
}
inline void DungeonRoom::clear_initial_enemies() {
  initial_enemies_.Clear();
}
inline ::dungeonGame::protocol::Enemy* DungeonRoom::mutable_initial_enemies(int index) {
  // @@protoc_insertion_point(field_mutable:dungeonGame.protocol.DungeonRoom.initial_enemies)
  return initial_enemies_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Enemy >*
DungeonRoom::mutable_initial_enemies() {
  // @@protoc_insertion_point(field_mutable_list:dungeonGame.protocol.DungeonRoom.initial_enemies)
  return &initial_enemies_;
}
inline const ::dungeonGame::protocol::Enemy& DungeonRoom::initial_enemies(int index) const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.initial_enemies)
  return initial_enemies_.Get(index);
}
inline ::dungeonGame::protocol::Enemy* DungeonRoom::add_initial_enemies() {
  // @@protoc_insertion_point(field_add:dungeonGame.protocol.DungeonRoom.initial_enemies)
  return initial_enemies_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Enemy >&
DungeonRoom::initial_enemies() const {
  // @@protoc_insertion_point(field_list:dungeonGame.protocol.DungeonRoom.initial_enemies)
  return initial_enemies_;
}

// repeated .dungeonGame.protocol.Item spawnable_items = 6;
inline int DungeonRoom::spawnable_items_size() const {
  return spawnable_items_.size();
}
inline void DungeonRoom::clear_spawnable_items() {
  spawnable_items_.Clear();
}
inline ::dungeonGame::protocol::Item* DungeonRoom::mutable_spawnable_items(int index) {
  // @@protoc_insertion_point(field_mutable:dungeonGame.protocol.DungeonRoom.spawnable_items)
  return spawnable_items_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Item >*
DungeonRoom::mutable_spawnable_items() {
  // @@protoc_insertion_point(field_mutable_list:dungeonGame.protocol.DungeonRoom.spawnable_items)
  return &spawnable_items_;
}
inline const ::dungeonGame::protocol::Item& DungeonRoom::spawnable_items(int index) const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.DungeonRoom.spawnable_items)
  return spawnable_items_.Get(index);
}
inline ::dungeonGame::protocol::Item* DungeonRoom::add_spawnable_items() {
  // @@protoc_insertion_point(field_add:dungeonGame.protocol.DungeonRoom.spawnable_items)
  return spawnable_items_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::dungeonGame::protocol::Item >&
DungeonRoom::spawnable_items() const {
  // @@protoc_insertion_point(field_list:dungeonGame.protocol.DungeonRoom.spawnable_items)
  return spawnable_items_;
}

// -------------------------------------------------------------------

// Enemy

// string type = 1;
inline void Enemy::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Enemy::type() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Enemy.type)
  return type_.GetNoArena();
}
inline void Enemy::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Enemy.type)
}
#if LANG_CXX11
inline void Enemy::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dungeonGame.protocol.Enemy.type)
}
#endif
inline void Enemy::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dungeonGame.protocol.Enemy.type)
}
inline void Enemy::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dungeonGame.protocol.Enemy.type)
}
inline ::std::string* Enemy::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:dungeonGame.protocol.Enemy.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Enemy::release_type() {
  // @@protoc_insertion_point(field_release:dungeonGame.protocol.Enemy.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Enemy::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:dungeonGame.protocol.Enemy.type)
}

// float x = 2;
inline void Enemy::clear_x() {
  x_ = 0;
}
inline float Enemy::x() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Enemy.x)
  return x_;
}
inline void Enemy::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Enemy.x)
}

// float y = 3;
inline void Enemy::clear_y() {
  y_ = 0;
}
inline float Enemy::y() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Enemy.y)
  return y_;
}
inline void Enemy::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Enemy.y)
}

// int32 health = 4;
inline void Enemy::clear_health() {
  health_ = 0;
}
inline ::google::protobuf::int32 Enemy::health() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Enemy.health)
  return health_;
}
inline void Enemy::set_health(::google::protobuf::int32 value) {
  
  health_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Enemy.health)
}

// -------------------------------------------------------------------

// Item

// int32 item_id = 1;
inline void Item::clear_item_id() {
  item_id_ = 0;
}
inline ::google::protobuf::int32 Item::item_id() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Item.item_id)
  return item_id_;
}
inline void Item::set_item_id(::google::protobuf::int32 value) {
  
  item_id_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Item.item_id)
}

// string name = 2;
inline void Item::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Item::name() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.Item.name)
  return name_.GetNoArena();
}
inline void Item::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.Item.name)
}
#if LANG_CXX11
inline void Item::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dungeonGame.protocol.Item.name)
}
#endif
inline void Item::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dungeonGame.protocol.Item.name)
}
inline void Item::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dungeonGame.protocol.Item.name)
}
inline ::std::string* Item::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:dungeonGame.protocol.Item.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Item::release_name() {
  // @@protoc_insertion_point(field_release:dungeonGame.protocol.Item.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Item::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:dungeonGame.protocol.Item.name)
}

// -------------------------------------------------------------------

// RoomRequest

// int32 seed = 1;
inline void RoomRequest::clear_seed() {
  seed_ = 0;
}
inline ::google::protobuf::int32 RoomRequest::seed() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.RoomRequest.seed)
  return seed_;
}
inline void RoomRequest::set_seed(::google::protobuf::int32 value) {
  
  seed_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.RoomRequest.seed)
}

// int32 floor_level = 2;
inline void RoomRequest::clear_floor_level() {
  floor_level_ = 0;
}
inline ::google::protobuf::int32 RoomRequest::floor_level() const {
  // @@protoc_insertion_point(field_get:dungeonGame.protocol.RoomRequest.floor_level)
  return floor_level_;
}
inline void RoomRequest::set_floor_level(::google::protobuf::int32 value) {
  
  floor_level_ = value;
  // @@protoc_insertion_point(field_set:dungeonGame.protocol.RoomRequest.floor_level)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace dungeonGame

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_game_5fprotocol_2eproto
