// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game_protocol.proto

#include "game_protocol.pb.h"
#include "game_protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace dungeonGame {
namespace protocol {

static const char* DungeonArchitect_method_names[] = {
  "/dungeonGame.protocol.DungeonArchitect/GetNextRoom",
};

std::unique_ptr< DungeonArchitect::Stub> DungeonArchitect::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DungeonArchitect::Stub> stub(new DungeonArchitect::Stub(channel));
  return stub;
}

DungeonArchitect::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetNextRoom_(DungeonArchitect_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DungeonArchitect::Stub::GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::dungeonGame::protocol::DungeonRoom* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetNextRoom_, context, request, response);
}

void DungeonArchitect::Stub::experimental_async::GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetNextRoom_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>* DungeonArchitect::Stub::AsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::dungeonGame::protocol::DungeonRoom>::Create(channel_.get(), cq, rpcmethod_GetNextRoom_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>* DungeonArchitect::Stub::PrepareAsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::dungeonGame::protocol::DungeonRoom>::Create(channel_.get(), cq, rpcmethod_GetNextRoom_, context, request, false);
}

DungeonArchitect::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DungeonArchitect_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DungeonArchitect::Service, ::dungeonGame::protocol::RoomRequest, ::dungeonGame::protocol::DungeonRoom>(
          std::mem_fn(&DungeonArchitect::Service::GetNextRoom), this)));
}

DungeonArchitect::Service::~Service() {
}

::grpc::Status DungeonArchitect::Service::GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dungeonGame
}  // namespace protocol

