// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game_protocol.proto
#ifndef GRPC_game_5fprotocol_2eproto__INCLUDED
#define GRPC_game_5fprotocol_2eproto__INCLUDED

#include "game_protocol.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace dungeonGame {
namespace protocol {

class DungeonArchitect final {
 public:
  static constexpr char const* service_full_name() {
    return "dungeonGame.protocol.DungeonArchitect";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::dungeonGame::protocol::DungeonRoom* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>> AsyncGetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>>(AsyncGetNextRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>> PrepareAsyncGetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>>(PrepareAsyncGetNextRoomRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>* AsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dungeonGame::protocol::DungeonRoom>* PrepareAsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::dungeonGame::protocol::DungeonRoom* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>> AsyncGetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>>(AsyncGetNextRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>> PrepareAsyncGetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>>(PrepareAsyncGetNextRoomRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetNextRoom(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>* AsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dungeonGame::protocol::DungeonRoom>* PrepareAsyncGetNextRoomRaw(::grpc::ClientContext* context, const ::dungeonGame::protocol::RoomRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetNextRoom_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetNextRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetNextRoom() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetNextRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNextRoom(::grpc::ServerContext* context, ::dungeonGame::protocol::RoomRequest* request, ::grpc::ServerAsyncResponseWriter< ::dungeonGame::protocol::DungeonRoom>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetNextRoom<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetNextRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetNextRoom() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetNextRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetNextRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetNextRoom() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetNextRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetNextRoom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetNextRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetNextRoom() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::dungeonGame::protocol::RoomRequest, ::dungeonGame::protocol::DungeonRoom>(std::bind(&WithStreamedUnaryMethod_GetNextRoom<BaseClass>::StreamedGetNextRoom, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetNextRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetNextRoom(::grpc::ServerContext* context, const ::dungeonGame::protocol::RoomRequest* request, ::dungeonGame::protocol::DungeonRoom* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetNextRoom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dungeonGame::protocol::RoomRequest,::dungeonGame::protocol::DungeonRoom>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetNextRoom<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetNextRoom<Service > StreamedService;
};

}  // namespace protocol
}  // namespace dungeonGame


#endif  // GRPC_game_5fprotocol_2eproto__INCLUDED
