// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_protocol.proto

#include "game_protocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_game_5fprotocol_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_game_5fprotocol_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Enemy;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_game_5fprotocol_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Item;
}  // namespace protobuf_game_5fprotocol_2eproto
namespace dungeonGame {
namespace protocol {
class DungeonRoomDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DungeonRoom>
      _instance;
} _DungeonRoom_default_instance_;
class EnemyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Enemy>
      _instance;
} _Enemy_default_instance_;
class ItemDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Item>
      _instance;
} _Item_default_instance_;
class RoomRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RoomRequest>
      _instance;
} _RoomRequest_default_instance_;
}  // namespace protocol
}  // namespace dungeonGame
namespace protobuf_game_5fprotocol_2eproto {
static void InitDefaultsDungeonRoom() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dungeonGame::protocol::_DungeonRoom_default_instance_;
    new (ptr) ::dungeonGame::protocol::DungeonRoom();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dungeonGame::protocol::DungeonRoom::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_DungeonRoom =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsDungeonRoom}, {
      &protobuf_game_5fprotocol_2eproto::scc_info_Enemy.base,
      &protobuf_game_5fprotocol_2eproto::scc_info_Item.base,}};

static void InitDefaultsEnemy() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dungeonGame::protocol::_Enemy_default_instance_;
    new (ptr) ::dungeonGame::protocol::Enemy();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dungeonGame::protocol::Enemy::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Enemy =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEnemy}, {}};

static void InitDefaultsItem() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dungeonGame::protocol::_Item_default_instance_;
    new (ptr) ::dungeonGame::protocol::Item();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dungeonGame::protocol::Item::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Item =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsItem}, {}};

static void InitDefaultsRoomRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::dungeonGame::protocol::_RoomRequest_default_instance_;
    new (ptr) ::dungeonGame::protocol::RoomRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dungeonGame::protocol::RoomRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RoomRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRoomRequest}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_DungeonRoom.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Enemy.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Item.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RoomRequest.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, room_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, room_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, initial_enemies_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::DungeonRoom, spawnable_items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Enemy, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Enemy, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Enemy, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Enemy, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Enemy, health_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Item, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Item, item_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::Item, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::RoomRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::RoomRequest, seed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dungeonGame::protocol::RoomRequest, floor_level_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::dungeonGame::protocol::DungeonRoom)},
  { 11, -1, sizeof(::dungeonGame::protocol::Enemy)},
  { 20, -1, sizeof(::dungeonGame::protocol::Item)},
  { 27, -1, sizeof(::dungeonGame::protocol::RoomRequest)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::dungeonGame::protocol::_DungeonRoom_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dungeonGame::protocol::_Enemy_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dungeonGame::protocol::_Item_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dungeonGame::protocol::_RoomRequest_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "game_protocol.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023game_protocol.proto\022\024dungeonGame.proto"
      "col\"\273\001\n\013DungeonRoom\022\017\n\007room_id\030\001 \001(\005\022\021\n\t"
      "room_type\030\002 \001(\t\022\r\n\005width\030\003 \001(\005\022\016\n\006height"
      "\030\004 \001(\005\0224\n\017initial_enemies\030\005 \003(\0132\033.dungeo"
      "nGame.protocol.Enemy\0223\n\017spawnable_items\030"
      "\006 \003(\0132\032.dungeonGame.protocol.Item\";\n\005Ene"
      "my\022\014\n\004type\030\001 \001(\t\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022\016"
      "\n\006health\030\004 \001(\005\"%\n\004Item\022\017\n\007item_id\030\001 \001(\005\022"
      "\014\n\004name\030\002 \001(\t\"0\n\013RoomRequest\022\014\n\004seed\030\001 \001"
      "(\005\022\023\n\013floor_level\030\002 \001(\0052g\n\020DungeonArchit"
      "ect\022S\n\013GetNextRoom\022!.dungeonGame.protoco"
      "l.RoomRequest\032!.dungeonGame.protocol.Dun"
      "geonRoomb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 496);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "game_protocol.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_game_5fprotocol_2eproto
namespace dungeonGame {
namespace protocol {

// ===================================================================

void DungeonRoom::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DungeonRoom::kRoomIdFieldNumber;
const int DungeonRoom::kRoomTypeFieldNumber;
const int DungeonRoom::kWidthFieldNumber;
const int DungeonRoom::kHeightFieldNumber;
const int DungeonRoom::kInitialEnemiesFieldNumber;
const int DungeonRoom::kSpawnableItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DungeonRoom::DungeonRoom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fprotocol_2eproto::scc_info_DungeonRoom.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dungeonGame.protocol.DungeonRoom)
}
DungeonRoom::DungeonRoom(const DungeonRoom& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      initial_enemies_(from.initial_enemies_),
      spawnable_items_(from.spawnable_items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  room_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.room_type().size() > 0) {
    room_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.room_type_);
  }
  ::memcpy(&room_id_, &from.room_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&height_) -
    reinterpret_cast<char*>(&room_id_)) + sizeof(height_));
  // @@protoc_insertion_point(copy_constructor:dungeonGame.protocol.DungeonRoom)
}

void DungeonRoom::SharedCtor() {
  room_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&room_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&room_id_)) + sizeof(height_));
}

DungeonRoom::~DungeonRoom() {
  // @@protoc_insertion_point(destructor:dungeonGame.protocol.DungeonRoom)
  SharedDtor();
}

void DungeonRoom::SharedDtor() {
  room_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DungeonRoom::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DungeonRoom::descriptor() {
  ::protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DungeonRoom& DungeonRoom::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fprotocol_2eproto::scc_info_DungeonRoom.base);
  return *internal_default_instance();
}


void DungeonRoom::Clear() {
// @@protoc_insertion_point(message_clear_start:dungeonGame.protocol.DungeonRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  initial_enemies_.Clear();
  spawnable_items_.Clear();
  room_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&room_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&height_) -
      reinterpret_cast<char*>(&room_id_)) + sizeof(height_));
  _internal_metadata_.Clear();
}

bool DungeonRoom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dungeonGame.protocol.DungeonRoom)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 room_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &room_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string room_type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->room_type().data(), static_cast<int>(this->room_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dungeonGame.protocol.DungeonRoom.room_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 width = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 height = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_initial_enemies()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .dungeonGame.protocol.Item spawnable_items = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_spawnable_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dungeonGame.protocol.DungeonRoom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dungeonGame.protocol.DungeonRoom)
  return false;
#undef DO_
}

void DungeonRoom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dungeonGame.protocol.DungeonRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 room_id = 1;
  if (this->room_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->room_id(), output);
  }

  // string room_type = 2;
  if (this->room_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->room_type().data(), static_cast<int>(this->room_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.DungeonRoom.room_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->room_type(), output);
  }

  // int32 width = 3;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->width(), output);
  }

  // int32 height = 4;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->height(), output);
  }

  // repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->initial_enemies_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->initial_enemies(static_cast<int>(i)),
      output);
  }

  // repeated .dungeonGame.protocol.Item spawnable_items = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->spawnable_items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->spawnable_items(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dungeonGame.protocol.DungeonRoom)
}

::google::protobuf::uint8* DungeonRoom::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dungeonGame.protocol.DungeonRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 room_id = 1;
  if (this->room_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->room_id(), target);
  }

  // string room_type = 2;
  if (this->room_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->room_type().data(), static_cast<int>(this->room_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.DungeonRoom.room_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->room_type(), target);
  }

  // int32 width = 3;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->width(), target);
  }

  // int32 height = 4;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->height(), target);
  }

  // repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->initial_enemies_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->initial_enemies(static_cast<int>(i)), deterministic, target);
  }

  // repeated .dungeonGame.protocol.Item spawnable_items = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->spawnable_items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->spawnable_items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dungeonGame.protocol.DungeonRoom)
  return target;
}

size_t DungeonRoom::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dungeonGame.protocol.DungeonRoom)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .dungeonGame.protocol.Enemy initial_enemies = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->initial_enemies_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->initial_enemies(static_cast<int>(i)));
    }
  }

  // repeated .dungeonGame.protocol.Item spawnable_items = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->spawnable_items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->spawnable_items(static_cast<int>(i)));
    }
  }

  // string room_type = 2;
  if (this->room_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->room_type());
  }

  // int32 room_id = 1;
  if (this->room_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->room_id());
  }

  // int32 width = 3;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  // int32 height = 4;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DungeonRoom::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dungeonGame.protocol.DungeonRoom)
  GOOGLE_DCHECK_NE(&from, this);
  const DungeonRoom* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DungeonRoom>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dungeonGame.protocol.DungeonRoom)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dungeonGame.protocol.DungeonRoom)
    MergeFrom(*source);
  }
}

void DungeonRoom::MergeFrom(const DungeonRoom& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dungeonGame.protocol.DungeonRoom)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  initial_enemies_.MergeFrom(from.initial_enemies_);
  spawnable_items_.MergeFrom(from.spawnable_items_);
  if (from.room_type().size() > 0) {

    room_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.room_type_);
  }
  if (from.room_id() != 0) {
    set_room_id(from.room_id());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
}

void DungeonRoom::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dungeonGame.protocol.DungeonRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DungeonRoom::CopyFrom(const DungeonRoom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dungeonGame.protocol.DungeonRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DungeonRoom::IsInitialized() const {
  return true;
}

void DungeonRoom::Swap(DungeonRoom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DungeonRoom::InternalSwap(DungeonRoom* other) {
  using std::swap;
  CastToBase(&initial_enemies_)->InternalSwap(CastToBase(&other->initial_enemies_));
  CastToBase(&spawnable_items_)->InternalSwap(CastToBase(&other->spawnable_items_));
  room_type_.Swap(&other->room_type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(room_id_, other->room_id_);
  swap(width_, other->width_);
  swap(height_, other->height_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DungeonRoom::GetMetadata() const {
  protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Enemy::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Enemy::kTypeFieldNumber;
const int Enemy::kXFieldNumber;
const int Enemy::kYFieldNumber;
const int Enemy::kHealthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Enemy::Enemy()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fprotocol_2eproto::scc_info_Enemy.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dungeonGame.protocol.Enemy)
}
Enemy::Enemy(const Enemy& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&health_) -
    reinterpret_cast<char*>(&x_)) + sizeof(health_));
  // @@protoc_insertion_point(copy_constructor:dungeonGame.protocol.Enemy)
}

void Enemy::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&health_) -
      reinterpret_cast<char*>(&x_)) + sizeof(health_));
}

Enemy::~Enemy() {
  // @@protoc_insertion_point(destructor:dungeonGame.protocol.Enemy)
  SharedDtor();
}

void Enemy::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Enemy::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Enemy::descriptor() {
  ::protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Enemy& Enemy::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fprotocol_2eproto::scc_info_Enemy.base);
  return *internal_default_instance();
}


void Enemy::Clear() {
// @@protoc_insertion_point(message_clear_start:dungeonGame.protocol.Enemy)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&health_) -
      reinterpret_cast<char*>(&x_)) + sizeof(health_));
  _internal_metadata_.Clear();
}

bool Enemy::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dungeonGame.protocol.Enemy)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dungeonGame.protocol.Enemy.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float x = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float y = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 health = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &health_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dungeonGame.protocol.Enemy)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dungeonGame.protocol.Enemy)
  return false;
#undef DO_
}

void Enemy::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dungeonGame.protocol.Enemy)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.Enemy.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // float x = 2;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->x(), output);
  }

  // float y = 3;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->y(), output);
  }

  // int32 health = 4;
  if (this->health() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->health(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dungeonGame.protocol.Enemy)
}

::google::protobuf::uint8* Enemy::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dungeonGame.protocol.Enemy)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.Enemy.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // float x = 2;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->x(), target);
  }

  // float y = 3;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->y(), target);
  }

  // int32 health = 4;
  if (this->health() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->health(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dungeonGame.protocol.Enemy)
  return target;
}

size_t Enemy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dungeonGame.protocol.Enemy)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string type = 1;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // float x = 2;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // float y = 3;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // int32 health = 4;
  if (this->health() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->health());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Enemy::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dungeonGame.protocol.Enemy)
  GOOGLE_DCHECK_NE(&from, this);
  const Enemy* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Enemy>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dungeonGame.protocol.Enemy)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dungeonGame.protocol.Enemy)
    MergeFrom(*source);
  }
}

void Enemy::MergeFrom(const Enemy& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dungeonGame.protocol.Enemy)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.health() != 0) {
    set_health(from.health());
  }
}

void Enemy::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dungeonGame.protocol.Enemy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Enemy::CopyFrom(const Enemy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dungeonGame.protocol.Enemy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Enemy::IsInitialized() const {
  return true;
}

void Enemy::Swap(Enemy* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Enemy::InternalSwap(Enemy* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(x_, other->x_);
  swap(y_, other->y_);
  swap(health_, other->health_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Enemy::GetMetadata() const {
  protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Item::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Item::kItemIdFieldNumber;
const int Item::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Item::Item()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fprotocol_2eproto::scc_info_Item.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dungeonGame.protocol.Item)
}
Item::Item(const Item& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  item_id_ = from.item_id_;
  // @@protoc_insertion_point(copy_constructor:dungeonGame.protocol.Item)
}

void Item::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  item_id_ = 0;
}

Item::~Item() {
  // @@protoc_insertion_point(destructor:dungeonGame.protocol.Item)
  SharedDtor();
}

void Item::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Item::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Item::descriptor() {
  ::protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Item& Item::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fprotocol_2eproto::scc_info_Item.base);
  return *internal_default_instance();
}


void Item::Clear() {
// @@protoc_insertion_point(message_clear_start:dungeonGame.protocol.Item)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  item_id_ = 0;
  _internal_metadata_.Clear();
}

bool Item::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dungeonGame.protocol.Item)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 item_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &item_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dungeonGame.protocol.Item.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dungeonGame.protocol.Item)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dungeonGame.protocol.Item)
  return false;
#undef DO_
}

void Item::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dungeonGame.protocol.Item)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 item_id = 1;
  if (this->item_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->item_id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.Item.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dungeonGame.protocol.Item)
}

::google::protobuf::uint8* Item::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dungeonGame.protocol.Item)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 item_id = 1;
  if (this->item_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->item_id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dungeonGame.protocol.Item.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dungeonGame.protocol.Item)
  return target;
}

size_t Item::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dungeonGame.protocol.Item)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 item_id = 1;
  if (this->item_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->item_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Item::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dungeonGame.protocol.Item)
  GOOGLE_DCHECK_NE(&from, this);
  const Item* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Item>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dungeonGame.protocol.Item)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dungeonGame.protocol.Item)
    MergeFrom(*source);
  }
}

void Item::MergeFrom(const Item& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dungeonGame.protocol.Item)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.item_id() != 0) {
    set_item_id(from.item_id());
  }
}

void Item::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dungeonGame.protocol.Item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Item::CopyFrom(const Item& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dungeonGame.protocol.Item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Item::IsInitialized() const {
  return true;
}

void Item::Swap(Item* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Item::InternalSwap(Item* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(item_id_, other->item_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Item::GetMetadata() const {
  protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void RoomRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RoomRequest::kSeedFieldNumber;
const int RoomRequest::kFloorLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RoomRequest::RoomRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_5fprotocol_2eproto::scc_info_RoomRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:dungeonGame.protocol.RoomRequest)
}
RoomRequest::RoomRequest(const RoomRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&seed_, &from.seed_,
    static_cast<size_t>(reinterpret_cast<char*>(&floor_level_) -
    reinterpret_cast<char*>(&seed_)) + sizeof(floor_level_));
  // @@protoc_insertion_point(copy_constructor:dungeonGame.protocol.RoomRequest)
}

void RoomRequest::SharedCtor() {
  ::memset(&seed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floor_level_) -
      reinterpret_cast<char*>(&seed_)) + sizeof(floor_level_));
}

RoomRequest::~RoomRequest() {
  // @@protoc_insertion_point(destructor:dungeonGame.protocol.RoomRequest)
  SharedDtor();
}

void RoomRequest::SharedDtor() {
}

void RoomRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RoomRequest::descriptor() {
  ::protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RoomRequest& RoomRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_5fprotocol_2eproto::scc_info_RoomRequest.base);
  return *internal_default_instance();
}


void RoomRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dungeonGame.protocol.RoomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&seed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&floor_level_) -
      reinterpret_cast<char*>(&seed_)) + sizeof(floor_level_));
  _internal_metadata_.Clear();
}

bool RoomRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dungeonGame.protocol.RoomRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 seed = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 floor_level = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &floor_level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dungeonGame.protocol.RoomRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dungeonGame.protocol.RoomRequest)
  return false;
#undef DO_
}

void RoomRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dungeonGame.protocol.RoomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 seed = 1;
  if (this->seed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->seed(), output);
  }

  // int32 floor_level = 2;
  if (this->floor_level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->floor_level(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dungeonGame.protocol.RoomRequest)
}

::google::protobuf::uint8* RoomRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dungeonGame.protocol.RoomRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 seed = 1;
  if (this->seed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->seed(), target);
  }

  // int32 floor_level = 2;
  if (this->floor_level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->floor_level(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dungeonGame.protocol.RoomRequest)
  return target;
}

size_t RoomRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dungeonGame.protocol.RoomRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 seed = 1;
  if (this->seed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->seed());
  }

  // int32 floor_level = 2;
  if (this->floor_level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->floor_level());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RoomRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dungeonGame.protocol.RoomRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const RoomRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RoomRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dungeonGame.protocol.RoomRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dungeonGame.protocol.RoomRequest)
    MergeFrom(*source);
  }
}

void RoomRequest::MergeFrom(const RoomRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dungeonGame.protocol.RoomRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.seed() != 0) {
    set_seed(from.seed());
  }
  if (from.floor_level() != 0) {
    set_floor_level(from.floor_level());
  }
}

void RoomRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dungeonGame.protocol.RoomRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RoomRequest::CopyFrom(const RoomRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dungeonGame.protocol.RoomRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RoomRequest::IsInitialized() const {
  return true;
}

void RoomRequest::Swap(RoomRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RoomRequest::InternalSwap(RoomRequest* other) {
  using std::swap;
  swap(seed_, other->seed_);
  swap(floor_level_, other->floor_level_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RoomRequest::GetMetadata() const {
  protobuf_game_5fprotocol_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_game_5fprotocol_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace dungeonGame
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dungeonGame::protocol::DungeonRoom* Arena::CreateMaybeMessage< ::dungeonGame::protocol::DungeonRoom >(Arena* arena) {
  return Arena::CreateInternal< ::dungeonGame::protocol::DungeonRoom >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dungeonGame::protocol::Enemy* Arena::CreateMaybeMessage< ::dungeonGame::protocol::Enemy >(Arena* arena) {
  return Arena::CreateInternal< ::dungeonGame::protocol::Enemy >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dungeonGame::protocol::Item* Arena::CreateMaybeMessage< ::dungeonGame::protocol::Item >(Arena* arena) {
  return Arena::CreateInternal< ::dungeonGame::protocol::Item >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::dungeonGame::protocol::RoomRequest* Arena::CreateMaybeMessage< ::dungeonGame::protocol::RoomRequest >(Arena* arena) {
  return Arena::CreateInternal< ::dungeonGame::protocol::RoomRequest >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
