// <auto-generated />

using DungeonServer.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DungeonServer.Infrastructure.Migrations
{
    [DbContext(typeof(DungeonDbContext))]
    [Migration("20260219132740_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("RoomEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RoomEntityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.RoomExitEntity", b =>
                {
                    b.Property<int>("FromRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("ExitDirection")
                        .HasColumnType("integer");

                    b.Property<int>("ToRoomId")
                        .HasColumnType("integer");

                    b.HasKey("FromRoomId", "ExitDirection");

                    b.ToTable("RoomExits");
                });

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.HasOne("DungeonServer.Infrastructure.Persistence.Entities.RoomEntity", null)
                        .WithMany("Occupants")
                        .HasForeignKey("RoomEntityId");
                });

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.RoomExitEntity", b =>
                {
                    b.HasOne("DungeonServer.Infrastructure.Persistence.Entities.RoomEntity", null)
                        .WithMany("Exits")
                        .HasForeignKey("FromRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonServer.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Navigation("Exits");

                    b.Navigation("Occupants");
                });
#pragma warning restore 612, 618
        }
    }
}
